[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npx serve -s build -l 3000"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
REACT_APP_API_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
REACT_APP_BACKEND_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"

# Variables d'environnement à configurer dans Railway Dashboard
# REACT_APP_API_URL - URL de votre backend Railway
# REACT_APP_BACKEND_URL - URL de votre backend Railway
