[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
VITE_API_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"

# Variables d'environnement à configurer dans Railway Dashboard
# VITE_API_URL - URL de votre backend Railway
# VITE_BACKEND_URL - URL complète du backend
# VITE_HIDE_CONSOLE - Masquer les logs en production (true/false)
