[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

# ⚠️ IMPORTANT: Configurez ces variables dans Railway Dashboard (Variables → Raw Editor)
# VITE_API_URL = "https://church-production-9a34.up.railway.app"
# VITE_BACKEND_URL = "https://church-production-9a34.up.railway.app"
# VITE_HIDE_CONSOLE = "true"
# VITE_PERFORMANCE_TRACKING = "false"
#
# Ces variables sont utilisées pendant le BUILD Vite
