// Liste des villes françaises avec leurs populations
export const cityPopulations = [
    { name: 'Paris', population: 2161000 },
    { name: 'Marseille', population: 861635 },
    { name: 'Lyon', population: 513275 },
    { name: 'Toulouse', population: 479553 },
    { name: 'Nice', population: 342522 },
    { name: 'Nantes', population: 309346 },
    { name: 'Strasbourg', population: 280966 },
    { name: 'Montpellier', population: 285121 },
    { name: 'Bordeaux', population: 254436 },
    { name: 'Lille', population: 232787 },
    { name: 'Rennes', population: 217728 },
    { name: 'Reims', population: 180752 },
    { name: 'Saint-Étienne', population: 172565 },
    { name: 'Toulon', population: 171953 },
    { name: 'Le Havre', population: 170147 },
    { name: 'Grenoble', population: 158454 },
    { name: 'Dijon', population: 156854 },
    { name: 'Angers', population: 154508 },
    { name: 'Saint-Denis', population: 153810 },
    { name: 'Villeurbanne', population: 150659 },
    { name: 'Le Mans', population: 143252 },
    { name: 'Aix-en-Provence', population: 143097 },
    { name: 'Brest', population: 139456 },
    { name: 'Nîmes', population: 146709 },
    { name: 'Limoges', population: 132175 },
    { name: 'Clermont-Ferrand', population: 143886 },
    { name: 'Tours', population: 136463 },
    { name: 'Villejuif', population: 131824 },
    { name: 'Amiens', population: 133625 },
    { name: 'Metz', population: 118489 },
    { name: 'Besançon', population: 117912 },
    { name: 'Perpignan', population: 119656 },
    { name: 'Orléans', population: 114782 },
    { name: 'Mulhouse', population: 108942 },
    { name: 'Caen', population: 105354 },
    { name: 'Boulogne-Billancourt', population: 119808 },
    { name: 'Rouen', population: 110169 },
    { name: 'Nancy', population: 104260 },
    { name: 'Argenteuil', population: 107221 },
    { name: 'Montreuil', population: 104139 },
    { name: 'Saint-Paul', population: 103916 },
    { name: 'Roubaix', population: 98712 },
    { name: 'Tourcoing', population: 97442 },
    { name: 'Nanterre', population: 94525 },
    { name: 'Avignon', population: 91343 },
    { name: 'Créteil', population: 90195 },
    { name: 'Poitiers', population: 87698 },
    { name: 'Versailles', population: 85771 },
    { name: 'Pau', population: 77200 },
    { name: 'Colombes', population: 85177 },
    { name: 'Vitry-sur-Seine', population: 92909 },
    { name: 'Aulnay-sous-Bois', population: 82514 },
    { name: 'Asnières-sur-Seine', population: 86742 },
    { name: 'Courbevoie', population: 81603 },
    { name: 'Cherbourg-en-Cotentin', population: 80076 },
    { name: 'Rueil-Malmaison', population: 78145 },
    { name: 'Bourges', population: 64668 },
    { name: 'Le Cannet', population: 41531 },
    { name: 'Dunkerque', population: 86865 },
    { name: 'Saint-Maur-des-Fossés', population: 75214 },
    { name: 'Valence', population: 63848 },
    { name: 'Quimper', population: 63532 },
    { name: 'Antibes', population: 75820 },
    { name: 'Troyes', population: 61996 },
    { name: 'Auxerre', population: 34734 },
    { name: 'Bourgoin-Jallieu', population: 28447 },
    { name: 'Cannes', population: 73421 },
    { name: 'Calais', population: 72929 },
    { name: 'Saint-Brieuc', population: 44472 },
    { name: 'Saint-Herblain', population: 46352 },
    { name: 'Saint-Priest', population: 46845 },
    { name: 'La Rochelle', population: 75736 },
    { name: 'Rezé', population: 42068 },
    { name: 'Saint-André', population: 55653 },
    { name: 'Montauban', population: 60489 },
    { name: 'Chambery', population: 58753 },
    { name: 'Aix-les-Bains', population: 30812 },
    { name: 'Boulogne-sur-Mer', population: 42092 },
    { name: 'Châteauroux', population: 43442 },
    { name: 'Chalon-sur-Saône', population: 45166 },
    { name: 'Albi', population: 49532 },
    { name: 'Mâcon', population: 34350 },
    { name: 'Colmar', population: 67714 },
    { name: 'Dole', population: 23575 },
    { name: 'Épinal', population: 32006 },
    { name: 'Montbéliard', population: 25405 },
    { name: 'Valenciennes', population: 43336 },
    { name: 'Thionville', population: 40578 },
    { name: 'Tarbes', population: 43363 },
    { name: 'Haguenau', population: 35112 },
    { name: 'Charleville-Mézières', population: 46348 },
    { name: 'Évreux', population: 47533 },
    { name: 'Saint-Étienne-du-Rouvray', population: 28408 },
    { name: 'Drancy', population: 71043 },
    { name: 'Noisy-le-Grand', population: 66888 },
    { name: 'Ivry-sur-Seine', population: 63486 },
    { name: 'Évry-Courcouronnes', population: 67591 },
    { name: 'Villeneuve-d\'Ascq', population: 62408 },
    { name: 'Sarcelles', population: 58546 },
    { name: 'Le Blanc-Mesnil', population: 55519 },
    { name: 'Alfortville', population: 44818 },
    { name: 'Saint-Ouen', population: 53107 },
    { name: 'Neuilly-sur-Seine', population: 59940 },
    { name: 'Clichy', population: 62854 },
    { name: 'Pantin', population: 57001 },
    { name: 'Maisons-Alfort', population: 54843 },
    { name: 'Malakoff', population: 30420 },
    { name: 'Bagneux', population: 40336 },
    { name: 'Fontenay-sous-Bois', population: 52424 },
    { name: 'Issy-les-Moulineaux', population: 67198 },
    { name: 'Bondy', population: 54866 },
    { name: 'Bobigny', population: 54787 },
    { name: 'Les Lilas', population: 23001 },
    { name: 'Vincennes', population: 49568 },
    { name: 'Saint-Mandé', population: 22563 },
    { name: 'Montrouge', population: 50260 },
    { name: 'Bagnolet', population: 35773 },
    { name: 'Rosny-sous-Bois', population: 46527 },
    { name: 'Noisy-le-Sec', population: 45674 },
    { name: 'Le Pré-Saint-Gervais', population: 17050 },
    { name: 'Romainville', population: 47028 },
    { name: 'L\'Île-Saint-Denis', population: 8047 },
    { name: 'Le Raincy', population: 14481 },
    { name: 'Neuilly-Plaisance', population: 20778 },
    { name: 'Neuilly-sur-Marne', population: 35608 },
    { name: 'Gagny', population: 39902 },
    { name: 'Gournay-sur-Marne', population: 6787 },
    { name: 'Villemomble', population: 29968 },
    { name: 'Le Perreux-sur-Marne', population: 33902 },
    { name: 'Bry-sur-Marne', population: 16888 },
    { name: 'Champigny-sur-Marne', population: 76818 },
    { name: 'Saint-Maurice', population: 14568 },
    { name: 'Joinville-le-Pont', population: 19052 },
    { name: 'Nogent-sur-Marne', population: 31849 },
    { name: 'Sevran', population: 51249 },
    { name: 'Villepinte', population: 37725 },
    { name: 'Tremblay-en-France', population: 35885 },
    { name: 'Gonesse', population: 25677 },
    { name: 'Garges-lès-Gonesse', population: 42528 },
    { name: 'Goussainville', population: 30991 },
    { name: 'Villiers-le-Bel', population: 27145 },
    { name: 'Bezons', population: 28712 },
    { name: 'Puteaux', population: 44891 },
    { name: 'Levallois-Perret', population: 64110 },
    { name: 'Aubervilliers', population: 88625 },
    { name: 'La Courneuve', population: 43354 },
    { name: 'Épinay-sur-Seine', population: 54781 },
    { name: 'Villetaneuse', population: 12312 },
    { name: 'Pierrefitte-sur-Seine', population: 29561 },
    { name: 'Stains', population: 38105 },
    { name: 'Saint-Gratien', population: 20767 },
    { name: 'Enghien-les-Bains', population: 11325 },
    { name: 'Soisy-sous-Montmorency', population: 17818 },
    { name: 'Ermont', population: 28421 },
    { name: 'Eaubonne', population: 24476 },
    { name: 'Saint-Leu-la-Forêt', population: 15450 },
    { name: 'Taverny', population: 26436 },
    { name: 'Bessancourt', population: 8084 },
    { name: 'Frépillon', population: 3334 },
    { name: 'Butry-sur-Oise', population: 2308 },
    { name: 'Méry-sur-Oise', population: 9875 },
    { name: 'Mériel', population: 5200 },
    { name: 'Valmondois', population: 1234 },
    { name: 'L\'Isle-Adam', population: 11815 },
    { name: 'Parmain', population: 5600 },
    { name: 'Nesles-la-Vallée', population: 1774 },
    { name: 'Nointel', population: 823 },
    { name: 'Champagne-sur-Oise', population: 4756 },
    { name: 'Persan', population: 12500 },
    { name: 'Beaumont-sur-Oise', population: 9567 },
    { name: 'Bernes-sur-Oise', population: 2500 },
    { name: 'Bruyères-sur-Oise', population: 3500 }
];

// Fonction pour obtenir une ville par nom
export const getCityByName = (cityName) => {
    return cityPopulations.find(city =>
        city.name.toLowerCase() === cityName.toLowerCase()
    );
};

// Fonction pour filtrer les villes par nom (pour l'autocomplete)
export const filterCities = (searchTerm) => {
    if (!searchTerm || searchTerm.length < 2) return [];

    const normalizedSearch = searchTerm.toLowerCase();
    return cityPopulations
        .filter(city =>
            city.name.toLowerCase().includes(normalizedSearch)
        )
        .slice(0, 20); // Limiter à 20 résultats
};